name: Publish Workflow / Validation
description: It runs pre-publish checks

inputs:
  package_name:
    description: package's name
    required: true

runs:
  using: composite
  steps:
    - name: Run linters
      run: echo 'lint'
      shell: bash

    - name: Run build
      run: echo 'build'
      shell: bash

    - name: Run tests and linters
      run: echo 'test'
      shell: bash
