name: Publish Workflow / Setup
description: It setting up the repository environment for publish

runs:
  using: composite
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
        always-auth: true
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: YARN_ENABLE_SCRIPTS=false yarn install --immutable
      shell: bash

    - name: Set Git credentials
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
      shell: bash
